#!/bin/bash

export SBT_TEST_ARG="test-only com.devmaid.common.config.ConfigurationTest  -- -n \"ConvertFromTestJsonFile_invalidFormat_duplicateSourceFolder\""
echo "setting SBT_TEST_ARG to $SBT_TEST_ARG"
